"""update_models_schema

Revision ID: c68b183aa062
Revises: e50efb40f8ac
Create Date: 2025-02-24 12:38:09.578517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68b183aa062'
down_revision: Union[str, None] = 'e50efb40f8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('churches', sa.Column('virtuous', sa.Boolean(), nullable=True))
    op.add_column('churches', sa.Column('senior_pastor_first_name', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('senior_pastor_last_name', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('senior_pastor_phone', sa.String(length=50), nullable=True))
    op.add_column('churches', sa.Column('senior_pastor_email', sa.String(), nullable=True))
    op.add_column('churches', sa.Column('missions_pastor_first_name', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('missions_pastor_last_name', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('mission_pastor_phone', sa.String(length=50), nullable=True))
    op.add_column('churches', sa.Column('mission_pastor_email', sa.String(), nullable=True))
    op.add_column('churches', sa.Column('primary_contact_first_name', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('primary_contact_last_name', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('primary_contact_phone', sa.String(length=50), nullable=True))
    op.add_column('churches', sa.Column('primary_contact_email', sa.String(), nullable=True))
    op.add_column('churches', sa.Column('website', sa.String(), nullable=True))
    op.add_column('churches', sa.Column('denomination', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('congregation_size', sa.Integer(), nullable=True))
    op.add_column('churches', sa.Column('church_pipeline', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('priority', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('assigned_to', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('referred_by', sa.String(length=100), nullable=True))
    op.add_column('churches', sa.Column('info_given', sa.Text(), nullable=True))
    op.add_column('churches', sa.Column('reason_closed', sa.Text(), nullable=True))
    op.add_column('churches', sa.Column('year_founded', sa.Integer(), nullable=True))
    op.add_column('churches', sa.Column('date_closed', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'churches', 'contacts', ['id'], ['id'])
    op.drop_column('churches', 'name')
    op.drop_column('churches', 'email')
    op.drop_column('churches', 'phone')
    op.add_column('contacts', sa.Column('church_name', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('image', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('preferred_contact_method', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('initial_notes', sa.Text(), nullable=True))
    op.drop_column('contacts', 'notes')
    op.drop_column('contacts', 'name')
    op.add_column('people', sa.Column('spouse_first_name', sa.String(length=100), nullable=True))
    op.add_column('people', sa.Column('spouse_last_name', sa.String(length=100), nullable=True))
    op.add_column('people', sa.Column('virtuous', sa.Boolean(), nullable=True))
    op.add_column('people', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('people', sa.Column('home_country', sa.String(length=100), nullable=True))
    op.add_column('people', sa.Column('marital_status', sa.String(length=100), nullable=True))
    op.add_column('people', sa.Column('people_pipeline', sa.String(length=100), nullable=True))
    op.add_column('people', sa.Column('priority', sa.String(length=100), nullable=True))
    op.add_column('people', sa.Column('assigned_to', sa.String(length=100), nullable=True))
    op.add_column('people', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('people', sa.Column('referred_by', sa.String(length=100), nullable=True))
    op.add_column('people', sa.Column('info_given', sa.Text(), nullable=True))
    op.add_column('people', sa.Column('desired_service', sa.Text(), nullable=True))
    op.add_column('people', sa.Column('reason_closed', sa.Text(), nullable=True))
    op.add_column('people', sa.Column('date_closed', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'people', 'contacts', ['id'], ['id'])
    op.drop_column('people', 'address')
    op.drop_column('people', 'email')
    op.drop_column('people', 'phone')
    op.drop_column('people', 'name')
    op.drop_column('people', 'google_resource_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('google_resource_name', sa.VARCHAR(), nullable=True))
    op.add_column('people', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.add_column('people', sa.Column('phone', sa.VARCHAR(), nullable=True))
    op.add_column('people', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('people', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_column('people', 'date_closed')
    op.drop_column('people', 'reason_closed')
    op.drop_column('people', 'desired_service')
    op.drop_column('people', 'info_given')
    op.drop_column('people', 'referred_by')
    op.drop_column('people', 'source')
    op.drop_column('people', 'assigned_to')
    op.drop_column('people', 'priority')
    op.drop_column('people', 'people_pipeline')
    op.drop_column('people', 'marital_status')
    op.drop_column('people', 'home_country')
    op.drop_column('people', 'title')
    op.drop_column('people', 'virtuous')
    op.drop_column('people', 'spouse_last_name')
    op.drop_column('people', 'spouse_first_name')
    op.add_column('contacts', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.add_column('contacts', sa.Column('notes', sa.VARCHAR(), nullable=True))
    op.drop_column('contacts', 'initial_notes')
    op.drop_column('contacts', 'preferred_contact_method')
    op.drop_column('contacts', 'image')
    op.drop_column('contacts', 'last_name')
    op.drop_column('contacts', 'first_name')
    op.drop_column('contacts', 'church_name')
    op.add_column('churches', sa.Column('phone', sa.VARCHAR(), nullable=True))
    op.add_column('churches', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('churches', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'churches', type_='foreignkey')
    op.drop_column('churches', 'date_closed')
    op.drop_column('churches', 'year_founded')
    op.drop_column('churches', 'reason_closed')
    op.drop_column('churches', 'info_given')
    op.drop_column('churches', 'referred_by')
    op.drop_column('churches', 'source')
    op.drop_column('churches', 'assigned_to')
    op.drop_column('churches', 'priority')
    op.drop_column('churches', 'church_pipeline')
    op.drop_column('churches', 'congregation_size')
    op.drop_column('churches', 'denomination')
    op.drop_column('churches', 'website')
    op.drop_column('churches', 'primary_contact_email')
    op.drop_column('churches', 'primary_contact_phone')
    op.drop_column('churches', 'primary_contact_last_name')
    op.drop_column('churches', 'primary_contact_first_name')
    op.drop_column('churches', 'mission_pastor_email')
    op.drop_column('churches', 'mission_pastor_phone')
    op.drop_column('churches', 'missions_pastor_last_name')
    op.drop_column('churches', 'missions_pastor_first_name')
    op.drop_column('churches', 'senior_pastor_email')
    op.drop_column('churches', 'senior_pastor_phone')
    op.drop_column('churches', 'senior_pastor_last_name')
    op.drop_column('churches', 'senior_pastor_first_name')
    op.drop_column('churches', 'virtuous')
    # ### end Alembic commands ###
